field: b0e73a9b-5f88-4b6a-b2af-ea73cb90529e # Benefits
fieldLayouts:
  a5ce5cd2-7c7c-4c97-8b1c-43695304fe49:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9e6d4ea4-1e16-4299-b0f0-65391a2cd60c # content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f0c9217-3763-48a3-b32e-3b862b46023e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68045402-63a8-4d94-a03c-6bd244ae096d
        userCondition: null
fields:
  9e6d4ea4-1e16-4299-b0f0-65391a2cd60c: # content
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: contentText
    instructions: null
    name: content
    searchable: false
    settings:
      errorMessage: 'Unable to find component class ''craft\redactor\Field''.'
      expectedType: craft\redactor\Field
      settings:
        __assoc__:
          -
            - uiMode
            - enlarged
          -
            - redactorConfig
            - ''
          -
            - removeInlineStyles
            - 1
          -
            - removeEmptyTags
            - 1
          -
            - removeNbsp
            - 1
          -
            - availableVolumes
            - '*'
          -
            - availableTransforms
            - '*'
          -
            - showUnpermittedVolumes
            - false
          -
            - showUnpermittedFiles
            - false
          -
            - showHtmlButtonForNonAdmins
            - ''
          -
            - configSelectionMode
            - choose
          -
            - manualConfig
            - ''
          -
            - defaultTransform
            - ''
          -
            - purifierConfig
            - ''
          -
            - purifyHtml
            - 1
          -
            - columnType
            - text
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
handle: contentBlock
name: 'Content block'
sortOrder: 1
