field: 9a07a8c6-231c-40f6-9286-735c614949f3 # Social Menu
fieldLayouts:
  f45c1481-1c61-4d56-aea2-9ddcbd028ec1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 213a9208-f091-4c79-a266-70af6e2f76c2 # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b3b3bd2-c552-47f3-92c9-a5d27b0805bc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9231c9be-4db7-45fd-8b72-b50663cc54a5
        userCondition: null
fields:
  213a9208-f091-4c79-a266-70af6e2f76c2: # Link Text
    columnSuffix: ccqnxnnd
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: null
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: menu
name: menu
sortOrder: 1
