field: afad8d52-7f82-4e1c-a9e5-515e9b3cde9b # Botton Menu 
fieldLayouts:
  afdd33c8-8ffe-4304-a980-efa08393822a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1668a606-4b76-4d8f-ae82-4a48de2de39e # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecbd1aea-3d14-4ee8-9a13-9b82a1e3da8b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed198be6-2c05-4cea-9548-5a55a9f770e5 # Link Destination
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d061e65-5a64-435e-8a33-176c38d0fe0a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6cd34866-e0d5-43e8-b985-cd94660763ba
        userCondition: null
fields:
  1668a606-4b76-4d8f-ae82-4a48de2de39e: # Link Text
    columnSuffix: kiansqnv
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: null
    name: 'Link Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ed198be6-2c05-4cea-9548-5a55a9f770e5: # Link Destination
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkDestination
    instructions: null
    name: 'Link Destination'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: menu
name: menu
sortOrder: 1
