field: a7ec7afd-de0b-4d43-b4dc-21b23eb6fcc7 # Top Podcast Content
fieldLayouts:
  6565138c-cf29-4c23-853c-0a3e3f06b31f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 57e08976-97b0-4fb2-9080-da81cf721a19 # Top Podcast Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97b09807-dcbd-498c-858e-14b7efd5aad7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 07030979-fa8d-4eb8-8fee-087fdadc2f97 # Top Podcast Url
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 472ccf87-a7cd-4d3c-a368-fed3491e1014
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c0d4a15f-bd49-4efb-8130-69f142fe7870
        userCondition: null
fields:
  57e08976-97b0-4fb2-9080-da81cf721a19: # Top Podcast Name
    columnSuffix: atlmpsjs
    contentColumnType: text
    fieldGroup: null
    handle: topPodcastName
    instructions: null
    name: 'Top Podcast Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  07030979-fa8d-4eb8-8fee-087fdadc2f97: # Top Podcast Url
    columnSuffix: wmzzxyzd
    contentColumnType: text
    fieldGroup: null
    handle: topPodcastUrl
    instructions: 'must be a valid url'
    name: 'Top Podcast Url'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: topPodcastBlock
name: 'Top Podcast Block'
sortOrder: 1
