fieldLayouts:
  b3d80f2b-3868-4cd1-acd8-18e338058b92:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 42709bc1-746d-455b-93d6-26abf61c4299
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a641668-bcc9-4ed2-9bac-dfb91dc0d536 # Menu Fields
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4bd4a39-126e-4926-94a0-45d0ac99497e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 80d60514-67d0-4a61-af98-9dac834bf38b
        userCondition: null
handle: headerForVisitor
hasTitleField: false
name: 'Header for visitor'
section: 3264da0a-60aa-4c7e-8163-614a294d8b5c # Header for visitor
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
