fieldLayouts:
  98a79d8d-6402-4b05-ab8c-caefda3b465a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3b7fcef8-3f4d-4f02-9347-281e8466ac42
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ccc08331-4bc8-462c-b58d-882376a5bcd9 # FAQ Data
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7b055e7-54ae-4f58-9854-ca864a022c27
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 134a995e-5e1d-4f29-8521-d79ccb2bbef2 # Forums Data
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6304d855-be54-4978-8d4f-64f35dcc616c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 562b6ce1-5ac3-42e1-b36b-fba73b423d40
        userCondition: null
handle: helpCenter
hasTitleField: false
name: 'Help Center'
section: 465f96b0-32c1-4ab2-a7d5-d99be3670e14 # Help Center
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
