fieldLayouts:
  c577eca1-10cd-4dfa-81d4-3d3e4cdd44a3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8b2f57f2-b799-459f-a7f3-6c5d87e76ddb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 61951db9-d35c-4c59-8cd8-126b82665bf5
        userCondition: null
fs: logo
handle: logo
name: logo
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: logo
transformSubpath: ''
