fieldLayouts:
  482fe598-eb07-4011-ae87-5435ffe1e6d1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: dcf38d4b-05f1-4ba6-b2ae-a6c80e7addc2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0fd7422b-7851-47a4-8daf-70e6d7ba05ff
        userCondition: null
fs: logoPodspun
handle: logoPodspun
name: 'logo podspun '
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
