columnSuffix: mkbsjntc
contentColumnType: text
fieldGroup: cbc44b0f-6526-462f-ac84-129a825f0845 # Get Started Group
handle: benefitSectionHeading
instructions: null
name: 'Benefit Section Heading'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
