columnSuffix: null
contentColumnType: string
fieldGroup: f9d182f2-6c0b-4047-9502-01fe9a39d18d # Menu Group
handle: bottonMenu
instructions: null
name: 'Botton Menu '
searchable: false
settings:
  contentTable: '{{%matrixcontent_bottonmenu}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
