columnSuffix: null
contentColumnType: string
fieldGroup: a446726b-85cb-4499-8f96-fd14c491daf7 # Common
handle: navigation
instructions: null
name: 'Navigation Fields'
searchable: false
settings:
  contentTable: '{{%matrixcontent_navigation}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
