defaultPlacement: end
enableVersioning: true
handle: setting
name: setting
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  894afd1c-6b97-4b33-8619-8218c9a05d39: # podspun
    enabledByDefault: true
    hasUrls: true
    template: setting/_entry
    uriFormat: setting
type: single
